---
permalink: rhel-install/task-modify-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: modify, default, password policy 
summary: 'O OnCommand Workflow Automation (WFA) está configurado para impor uma política de senha para usuários locais. Pode modificar a política de palavra-passe predefinida.' 
---
= Modifique a política de senha padrão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O OnCommand Workflow Automation (WFA) está configurado para impor uma política de senha para usuários locais. Pode modificar a política de palavra-passe predefinida.

Você deve ter feito login no sistema host WFA como um usuário root.

* O caminho de instalação padrão DO WFA é usado neste procedimento.
+
Se você alterou o local padrão durante a instalação, você deve usar o caminho de instalação alterado DO WFA.

* O comando para a política de senha padrão é ./wfa --password-policy.
+
O padrão é "minLength true,8;specialChar true,1;digitalChar true,1;lowcase Char true,1;uppercasChar true,1;whitespaceChar false" . Isso indica que a política de senha padrão deve ter um comprimento mínimo de oito carateres, deve conter pelo menos 1 carateres especiais, 1 dígitos, 1 carateres minúsculos, 1 carateres maiúsculos e nenhum espaço.



.Passos
. No prompt do shell, navegue para o seguinte diretório no servidor WFA: WFA_install_location/wfa/bin/
. Modifique a política de senha padrão digitando o seguinte comando:
+
`./wfa --password-policy=PasswordPolicyString --restart=WFA`


