---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Se você Esqueceu a senha do usuário admin que criou ao instalar o servidor OnCommand Workflow Automation (WFA), você pode redefini-la.' 
---
= Redefina a senha de administrador criada durante a instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você Esqueceu a senha do usuário admin que criou ao instalar o servidor OnCommand Workflow Automation (WFA), você pode redefini-la.

* Você deve ter o root Privileges para o sistema Linux no qual você instalou O WFA.
* Os serviços WFA devem estar em execução.
* Este procedimento redefine apenas a palavra-passe do utilizador admin criado durante a instalação DO WFA.
+
Não é possível redefinir a senha de outros usuários admin DO WFA que você criou após a instalação DO WFA.

* Este procedimento não aplica a política de palavra-passe que configurou.
+
Portanto, você deve inserir uma senha que esteja em conformidade com sua política de senha ou alterar a senha da interface do usuário DO WFA depois de redefinir a senha.



.Passos
. Como usuário root, faça login no sistema Linux no qual O WFA está instalado.
. No prompt do shell, navegue para o seguinte diretório no servidor WFA: WFA_install_location/wfa/bin/
. Introduza o seguinte comando:
+
`./wfa --admin-password [--password=PASS]`

+
Se não tiver fornecido uma palavra-passe, tem de introduzir a palavra-passe quando lhe for pedido.

. No prompt do shell, siga as instruções na tela.

