---
settings:
  name: OnCommand Workflow Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: OnCommand Workflow Automation docs
    url: "/index.html"
  - title: Notas de lançamento
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: Avisos legais
    url: "/reference-legal-notices.html"
