---
permalink: windows-install/concept-known-limitations-and-enhancements.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, limitations, enhancements 
summary: 'O OnCommand Workflow Automation (WFA) 5,1 inclui algumas limitações e recursos não suportados que você deve estar ciente antes de instalar e configurar O WFA.' 
---
= Limitações e melhorias conhecidas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O OnCommand Workflow Automation (WFA) 5,1 inclui algumas limitações e recursos não suportados que você deve estar ciente antes de instalar e configurar O WFA.

* *Criando nomes de categorias*
+
** Quando um hífen (-) é usado em um nome de categoria, ele é substituído por um espaço assim que a categoria é salva. Por exemplo, se o nome da categoria "abc-xyz" for fornecido, o nome da categoria será salvo como "abc xyz", com o hífen removido. Para evitar esse problema, não use hífens em nomes de categorias.
** Quando um ponto-e-vírgula (:) é usado em um nome de categoria, a cadeia de texto antes do ponto-e-vírgula é ignorada quando a categoria é salva. Por exemplo, se o nome da categoria "abc : xyz" for fornecido, o nome da categoria será salvo como "xyz", com a string "abc" removida. Para evitar esse problema, não use dois pontos em nomes de categorias.
** Não há verificação para evitar que duas categorias tenham o mesmo nome. No entanto, isso causa um problema ao selecionar essas categorias no painel de navegação. Para evitar este problema, certifique-se de que cada nome de categoria é único.



