---
permalink: windows-install/task-back-up-and-restore-the-wfa-database-and-configurations-windows.html 
sidebar: sidebar 
keywords: back up, restore, oncommand, workflow, automation, database, configurations windows 
summary: 'Você pode fazer backup e restaurar o banco de dados OnCommand Workflow Automation (WFA) e as configurações compatíveis para que você possa recuperar os dados em caso de desastre. As configurações suportadas incluem acesso a dados, tempo limite HTTP e certificados SSL.' 
---
= Faça backup e restaure o banco de dados e configurações do OnCommand Workflow Automation no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer backup e restaurar o banco de dados OnCommand Workflow Automation (WFA) e as configurações compatíveis para que você possa recuperar os dados em caso de desastre. As configurações suportadas incluem acesso a dados, tempo limite HTTP e certificados SSL.

Você precisa ter Privileges credenciais de administrador ou arquiteto.

Você deve criar o backup em um local seguro, pois a restauração do backup fornecerá acesso a todos os sistemas de armazenamento acessados pelo WFA.


NOTE: Você só pode usar os comandos de CLI ou APIS REST para operações abrangentes de backup e restauração durante a recuperação de desastres. Não é possível usar a IU da Web para criar um backup durante a recuperação de desastres em um ambiente de alta disponibilidade.

.Passos
. Faça backup de seus bancos de dados e configurações existentes.
+
link:reference-backing-up-of-the-oncommand-workflow-automation-database.html["Fazer backup do banco de dados OnCommand Workflow Automation"]

. Restaure um backup anterior de seus bancos de dados e configurações.
+
link:concept-restoring-the-wfa-database.html["Restaurar a base de dados OnCommand Workflow Automation"]


