---
permalink: windows-install/task-reset-the-admin-password-created-during-installation.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Se você Esqueceu a senha do usuário administrador que criou durante a instalação do servidor OnCommand Workflow Automation (WFA), você pode redefinir a senha.' 
---
= Redefina a senha de administrador criada durante a instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você Esqueceu a senha do usuário administrador que criou durante a instalação do servidor OnCommand Workflow Automation (WFA), você pode redefinir a senha.

* Você deve ter o administrador Privileges para o sistema Windows no qual você instalou O WFA.
* Os serviços WFA devem estar em execução.
* Este procedimento redefine apenas a palavra-passe do utilizador admin que foi criada durante a instalação DO WFA.
+
Não é possível redefinir a senha de outros usuários admin DO WFA que você criou após a instalação DO WFA.

* Este procedimento não aplica a política de palavra-passe que configurou.
+
Você deve inserir uma senha que esteja em conformidade com sua política de senha ou alterar a senha da interface do usuário DO WFA depois de redefinir a senha.



.Passos
. Abra um prompt de comando e navegue até o seguinte diretório: `WFA_install_location\WFA\bin\`
. Introduza o seguinte comando:
+
`wfa --admin-password [--password=PASS]`

+
Se você não fornecer uma senha no comando, você deve digitar a senha quando solicitado.

. No prompt de comando, siga as instruções na tela para redefinir a senha de administrador.

