---
permalink: windows-install/task-migrate-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: migrate, oncommand, workflow, automation, installation 
summary: 'Você pode migrar uma instalação do OnCommand Workflow Automation (WFA) para manter a chave de banco de dados exclusiva DO WFA instalada durante a instalação DO WFA. Por exemplo, você pode migrar a instalação DO WFA de um servidor Windows 2012 para um servidor Windows 2016.' 
---
= Migrar a instalação do OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode migrar uma instalação do OnCommand Workflow Automation (WFA) para manter a chave de banco de dados exclusiva DO WFA instalada durante a instalação DO WFA. Por exemplo, você pode migrar a instalação DO WFA de um servidor Windows 2012 para um servidor Windows 2016.

* Você deve executar este procedimento somente quando quiser migrar uma instalação DO WFA que inclua a chave do banco de dados DO WFA para um servidor diferente.
* Uma restauração de banco de dados WFA não migra a CHAVE WFA.
* A migração de uma instalação DO WFA não migra os certificados SSL.
* O caminho de instalação padrão DO WFA é usado neste procedimento.
+
Se você alterou o local padrão durante a instalação, você deve usar o caminho de instalação alterado DO WFA.



.Passos
. Acesse O WFA através de um navegador da Web como administrador.
. Faça backup do banco de dados DO WFA.
. Abra um prompt de comando no servidor WFA e mude os diretórios para o seguinte local: `c:\Program Files\NetApp\WFA\bin`
. Digite o seguinte no prompt de comando para obter a chave do banco de dados:
+
`wfa.cmd -key`

. Observe a chave do banco de dados exibida.
. Desinstale O WFA.
. Instale O WFA no sistema necessário.
. Abra o prompt de comando no novo servidor WFA e mude os diretórios para o seguinte local: `c:\Program Files\NetApp\WFA\bin`
. Digite o seguinte no prompt de comando para instalar a chave do banco de dados:
+
`wfa.cmd -key=yourdatabasekey`

+
Yourdatabasekey é a chave que você observou da instalação anterior DO WFA.

. Restaure o banco de dados WFA a partir do backup que você criou.

