---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password policy, windows 
summary: 'O OnCommand Workflow Automation (WFA) aplica uma política de senha para usuários locais. Você pode modificar a política de senha padrão para definir uma senha de acordo com sua exigência.' 
---
= Modifique a política de senha padrão para o Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O OnCommand Workflow Automation (WFA) aplica uma política de senha para usuários locais. Você pode modificar a política de senha padrão para definir uma senha de acordo com sua exigência.

Você deve estar conetado ao sistema host WFA como um usuário root.

* O caminho de instalação padrão DO WFA é usado neste procedimento.
+
Se você alterou o local padrão durante a instalação, você deve usar o caminho de instalação personalizado DO WFA.

* O comando para modificar a política de senha padrão é .
+
A configuração padrão é "minLength true,8;specialChar true,1;digitalChar true,1;lowcase Char true,1;uppercasChar true,1;whitespaceChar false". De acordo com essa configuração para a política de senha padrão, a senha deve ter um comprimento mínimo de oito carateres, deve conter pelo menos um caractere especial, um dígito, um caractere minúsculo e um caractere maiúsculo, e não deve conter espaços.



.Passos
. No prompt de comando, navegue para o seguinte diretório no servidor WFA:
+
`WFA_install_location/wfa/bin/`

. Modificar a política de palavra-passe predefinida:
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`


