---
permalink: windows-install/task-install-workflow-automation-on-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, install, windows 
summary: 'É possível instalar o OnCommand Workflow Automation (WFA) para criar e personalizar fluxos de trabalho de storage para automatizar as tarefas de storage executadas no ambiente.' 
---
= Instale o OnCommand Workflow Automation no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível instalar o OnCommand Workflow Automation (WFA) para criar e personalizar fluxos de trabalho de storage para automatizar as tarefas de storage executadas no ambiente.

* Você deve ter revisado os pré-requisitos de instalação.
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[Pré-requisitos para instalar o Workflow Automation]

* Se você estiver instalando O WFA em um sistema onde O WFA foi instalado anteriormente e depois desinstalado, você deve garantir que não há serviços WFA nesse sistema.
* Você deve ter baixado o instalador DO WFA do site de suporte da NetApp.
* Se você estiver instalando O WFA em uma máquina virtual (VM), o nome da VM não deve incluir o caractere sublinhado (_).
* ActiveState ActivePerl é instalado antes de instalar O WFA.
+
Esta instalação não afeta quaisquer outras instâncias do ActivePerl que você tenha instalado em seu SERVIDOR WFA.

* Antes de reinstalar O WFA 4,2 ou posterior, você deve excluir o diretório de dados MySQL se tiver desinstalado o MySQL.


.Passos
. Faça login no Windows usando uma conta com permissões administrativas.
. Abra o Explorador do Windows e, em seguida, navegue até ao diretório onde o ficheiro de instalação está localizado.
. Instale O WFA:
+
** Instalação interativa
+
... Clique com o botão direito do rato e execute o ficheiro executável (.exe) DO instalador DO WFA como utilizador admin.
... Clique em *seguinte*.
... Introduza as credenciais para o utilizador de administrador predefinido e, em seguida, clique em *seguinte*.
+
A senha de administrador padrão deve satisfazer os seguintes critérios:

+
**** Mínimo de oito carateres
**** Um caractere maiúsculo
**** Um caractere minúsculo
**** Um algarismo
**** Um caráter especial
**** Os seguintes carateres especiais não são suportados em uma senha e causam falha na instalação:
+
"" ; " > , " e ""

+
[NOTE]
====
Você deve observar as credenciais do usuário admin.

====


... Introduza um nome de utilizador e uma palavra-passe para o início de sessão DO serviço WFA. Para um utilizador de domínio, forneça um nome de utilizador no formato DOMÍNIO/UTILIZADOR. Para um usuário do sistema local, o formato é apenas um nome de usuário. O nome de utilizador predefinido é "wfa".
+
O instalador DO WFA cria um usuário local se não existir. Se existir um utilizador local e a palavra-passe introduzida for diferente da palavra-passe existente, O WFA atualiza a palavra-passe.

+
[NOTE]
====
Certifique-se de que a palavra-passe está em conformidade com a política de palavra-passe configurada para utilizadores locais no sistema. Se a senha não estiver em conformidade com a política de senha, a instalação falhará.

====
... Selecione as portas para a configuração DO WFA e clique em *Next*.
... Insira o nome de um site e o nome da sua empresa e clique em *Next*.
+
O nome do site pode incluir a localização da instalação DO WFA, por exemplo, Pittsburgh, PA.

... Se você quiser alterar o local de instalação padrão, selecione o local onde deseja instalar O WFA e clique em *Next*.
... Se você quiser alterar o local de instalação padrão para produtos de terceiros, selecione o local onde deseja instalar produtos de terceiros e clique em *Avançar*.
... Se você não quiser alterar o local padrão do banco de dados WFA, clique em *Next*.
... Clique em *Install* para continuar a instalação.
... Clique em *Finish* para concluir a instalação.
... Verifique se O WFA foi instalado com sucesso escolhendo uma das seguintes ações:
+
**** Acesse O WFA através de um navegador da Web.
**** Use o console dos Serviços do Windows para verificar se o serviço servidor WFA do NetApp e o serviço de banco de dados NetApp WFA estão em execução.




** Instalação silenciosa (a partir do prompt de comando):
+
 WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME=wfa_username WFA_ADMIN_PASSWORD=password WFA_ADMIN_CONFIRM_PASSWORD=confirm admin password / WFA_MYSQL_PASS=password CONFIRM_WFA_MYSQL_PASS=confirm MySQL password WFA_INSTALL_SITE=site WFA_INSTALL_ORGANIZATION=organization_name WFA_HTTP_PORT=port WFA_HTTPS_PORT=port INSTALLDIR=install_directory JDKINSTALLDIR=jdk_directory PerlDir=perl_directory MySqlInstallDir=mysql_directory WFA_SERVICE_LOGON_USERNAME=wfa service logon username WFA_SERVICE_LOGON_PASSWORD=wfa service logon user password MYSQL_DATA_DIR= mysql data directory /qr /l*v C:\install.log"
+
*Exemplo*

+
WFA-x64-V5.1.0.0.1-B5355278.exe 123 443 /s /v"WFA___80 1234___123 123 Perl64__NetApp___123_NetApp_NetApp_API_API_API_API_API_API_API_API_API_API_NetApp_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API__API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_API_NetApp

+
[NOTE]
====
A opção /qn não é suportada pelo WFA.

====
+
Os parâmetros de comando são os seguintes:

+
[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
WFA_ADMIN_USERNAME
 a| 
Nome do usuário Admin parâmetro opcional. Se você não especificar um valor, o valor padrão será admin.



 a| 
WFA_ADMIN_PASSWORD
 a| 
Senha do usuário Admin parâmetro obrigatório. A senha de administrador padrão deve satisfazer os seguintes critérios:

*** Mínimo de oito carateres
*** Um caractere maiúsculo
*** Um caractere minúsculo
*** Um algarismo
*** Um caráter especial
*** Os seguintes carateres não são permitidos e causam falha na entrada de senha:
+
"" ; " > , " e ""





 a| 
WFA_ADMIN_CONFIRM_PASSWORD
 a| 
Senha do usuário Admin parâmetro obrigatório



 a| 
WFA_MYSQL_PASS
 a| 
Senha do usuário MySQL parâmetro obrigatório



 a| 
CONFIRM_WFA_MYSQL_PASS
 a| 
Senha do usuário MySQL parâmetro obrigatório



 a| 
WFA_INSTALL_SITE
 a| 
Unidade organizacional em que O WFA está sendo instalado parâmetro obrigatório



 a| 
WFA_INSTALL_ORGANIZATION
 a| 
Organização ou nome da empresa em que O WFA está sendo instalado parâmetro obrigatório



 a| 
WFA_HTTP_PORT
 a| 
Parâmetro opcional da porta HTTP. Se você não especificar um valor, o valor padrão será 80.



 a| 
WFA_HTTPS_PORT
 a| 
Parâmetro opcional da porta HTTPS. Se você não especificar um valor, o valor padrão será 443.



 a| 
INSTALLDIR
 a| 
Caminho do diretório de instalação parâmetro opcional. Se você não especificar um valor, o caminho padrão será "C: Arquivos de programas/NetApp".



 a| 
JDKINSTALLDIR
 a| 
Caminho do diretório de instalação do JDK parâmetro opcional. Se você não especificar um valor, o caminho padrão será "C: Arquivos de programas NetApp".



 a| 
Perldir
 a| 
Caminho do diretório de instalação Perl parâmetro opcional. Se você não especificar um valor, o caminho padrão será "C: Perl64".



 a| 
MySqlInstallDir
 a| 
Caminho do diretório de instalação MySQL parâmetro opcional. Se você não especificar um valor, o caminho padrão será "C:



 a| 
WFA_SERVICE_LOGON_USERNAME
 a| 
Nome de usuário para o logon do serviço WFA parâmetro opcional. Se você não especificar um valor, o nome de usuário padrão é "wfa".

Para um utilizador de domínio, forneça um nome de utilizador no formato DOMÍNIO/UTILIZADOR. Para um usuário do sistema local, o formato é apenas um nome de usuário.

O instalador DO WFA cria um usuário local se não existir. Se existir um utilizador local e a palavra-passe introduzida for diferente da palavra-passe existente, O WFA atualiza a palavra-passe.

[NOTE]
====
Certifique-se de que a palavra-passe está em conformidade com a política de palavra-passe configurada para utilizadores locais no sistema. Se a senha não estiver em conformidade com a política de senha, a instalação falhará.

====


 a| 
WFA_SERVICE_LOGON_PASSWORD
 a| 
Palavra-passe para o parâmetro obrigatório de início de sessão DO serviço WFA



 a| 
MYSQL_DATA_DIR
 a| 
Diretório para dados MYSQL parâmetro opcional. Se você não especificar um valor, o caminho padrão será "C:

Disponível apenas para instalação nova.

|===




*Informações relacionadas*

https://mysupport.netapp.com/site/["Suporte à NetApp"^]
