---
permalink: windows-install/task-modify-the-transaction-timeout-setting-of-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: modify, transaction, timeout, set, oncommand, workflow, automation 
summary: 'Por padrão, a transação do banco de dados OnCommand Workflow Automation (WFA) expira em 300 segundos. Você pode aumentar a duração do tempo limite padrão ao restaurar um banco de dados WFA de grande porte a partir de um backup para evitar possíveis falhas na restauração do banco de dados.' 
---
= Modifique a configuração de tempo limite da transação do OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, a transação do banco de dados OnCommand Workflow Automation (WFA) expira em 300 segundos. Você pode aumentar a duração do tempo limite padrão ao restaurar um banco de dados WFA de grande porte a partir de um backup para evitar possíveis falhas na restauração do banco de dados.

Você deve ter feito login no sistema host DO WFA como administrador.

O caminho de instalação padrão DO WFA é usado neste procedimento. Se você alterou o local padrão durante a instalação, você deve usar o caminho de instalação alterado DO WFA.

.Passos
. Abra o Windows Explorer e navegue até o seguinte diretório:
+
`WFA_install_location\WFA\bin`

. Clique duas vezes no arquivo PS.cmd.
+
Um prompt de interface de linha de comando (CLI) do PowerShell é aberto com os módulos ONTAP e WFA carregados nele.

. No prompt, digite o seguinte:
+
`Set-WfaConfig -Name TransactionTimeOut -Seconds NumericValue`

+
`Set-WfaConfig -Name TransactionTimeOut -Seconds 1000`

. Quando solicitado, reinicie os serviços DO WFA.

