---
permalink: windows-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication settings 
summary: 'Você pode configurar o OnCommand Workflow Automation (WFA) para usar um servidor LDAP (Lightweight Directory Access Protocol) do Microsoft ative Directory (AD) para autenticação e autorização.' 
---
= Configure as definições de autenticação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o OnCommand Workflow Automation (WFA) para usar um servidor LDAP (Lightweight Directory Access Protocol) do Microsoft ative Directory (AD) para autenticação e autorização.

Você deve ter configurado um servidor LDAP do Microsoft AD em seu ambiente.

Apenas a autenticação LDAP do Microsoft AD é suportada para O WFA. Você não pode usar outros métodos de autenticação LDAP, incluindo o Microsoft AD Lightweight Directory Services (AD LDS) ou o Catálogo Global da Microsoft.


NOTE: Durante a comunicação, o LDAP envia o nome de utilizador e a palavra-passe em texto simples. No entanto, a comunicação LDAPS (LDAP Secure) é criptografada e segura.

.Passos
. Faça login NO WFA através de um navegador da Web como administrador.
. Clique em *Configurações* e, em *Configuração*, clique em *Autenticação*.
. Marque a caixa de seleção *Ativar ative Directory* .
. Introduza as informações necessárias nos campos:
+
.. Se você quiser usar o formato de domínio para usuários de domínio, substitua sAMAccountName por userPrincipalName no campo *User name attribute*.
.. Se forem necessários valores exclusivos para o seu ambiente, edite os campos obrigatórios.
.. Introduza o URI do servidor AD da seguinte forma: `ldap://active_directory_server_address\[:port\]`
+
LDAP://NB-T01.example.com[:389]

+
Se tiver ativado o LDAP sobre SSL, pode utilizar o seguinte formato URI: `ldaps://active_directory_server_address\[:port\]`

.. Adicione uma lista de nomes de grupos AD as funções necessárias.
+

NOTE: Você pode adicionar uma lista de nomes de grupos do AD às funções necessárias na janela grupos do ative Directory.



. Clique em *Salvar*.
. Se for necessária conetividade LDAP a uma matriz, configure o serviço WFA para efetuar logon como o usuário de domínio necessário:
+
.. Abra o console de serviços do Windows usando services.msc.
.. Clique duas vezes no serviço *servidor WFA NetApp*.
.. Na caixa de diálogo Propriedades do servidor NetApp WFA, clique na guia *Log on* e selecione *this account*.
.. Introduza o nome de utilizador e a palavra-passe do domínio e, em seguida, clique em *OK*.



