---
permalink: windows-install/task-disable-the-default-password-policy.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'O OnCommand Workflow Automation (WFA) está configurado para impor uma política de senha para usuários locais. Se não pretender utilizar a política de palavra-passe, pode desativá-la.' 
---
= Desative a política de senha padrão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O OnCommand Workflow Automation (WFA) está configurado para impor uma política de senha para usuários locais. Se não pretender utilizar a política de palavra-passe, pode desativá-la.

Você deve ter feito login no sistema host DO WFA como administrador.

O caminho de instalação padrão DO WFA é usado neste procedimento. Se você alterou o local padrão durante a instalação, você deve usar o caminho de instalação alterado DO WFA.

.Passos
. Abra o Windows Explorer e navegue até o seguinte diretório: `WFA_install_location\WFA\bin\.`
. Clique duas vezes no arquivo PS.cmd.
+
Um prompt de interface de linha de comando (CLI) do PowerShell é aberto com os módulos ONTAP e WFA carregados nele.

. No prompt, digite o seguinte:
+
`Set-WfaConfig -Name PasswordPolicy -Enable $false`

. Quando solicitado, reinicie os serviços DO WFA.

