---
permalink: windows-install/task-configure-wfa-with-mscs-using-configuration-scripts.html 
sidebar: sidebar 
keywords: configure, workflow, automation, mscs 
summary: 'Depois de instalar o Workflow Automation (WFA) no Microsoft Cluster Server (MSCS), você deve configurar O WFA para alta disponibilidade no MSCS usando scripts de configuração.' 
---
= Configurar a automação do fluxo de trabalho com MSCS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar o Workflow Automation (WFA) no Microsoft Cluster Server (MSCS), você deve configurar O WFA para alta disponibilidade no MSCS usando scripts de configuração.

Você deve ter criado um backup do WFA.


NOTE: Antes de iniciar a configuração, certifique-se de que a chave de criptografia WFA esteja definida de forma consistente em ambos os nós de cluster do MSCS. Se não estiver definido em ambos os nós, quando ocorrer failover, as credenciais não poderão ser descriptografadas no segundo nó causando falhas no fluxo de trabalho.

.Passos
. Faça login no primeiro nó do cluster MSCS e execute as seguintes etapas:
+
[cols="2*"]
|===
| Para... | Faça isso... 


 a| 
Windows 2012, Windows 2016, Windows 2019
 a| 
.. No Gerenciador de Cluster de failover, clique com o botão direito do Mouse em *funções de serviço*.
.. Selecione *Create Empty Service role* e renomeie a função para "WFA".
.. Adicione o recurso de endereço IP à função "WFA" recém-criada:
+
... No Gerenciador de Cluster de failover, clique com o botão direito do Mouse na função "WFA" recém-criada.
... Selecione *recurso* > *mais recursos* > *Endereço IP*.
... Configure o endereço IP do cluster.




|===
. Edite o `mscs_data_parameters.xml` arquivo e defina o caminho relativo para o diretório de dados MySQL:
+
[listing]
----
<dir>
    <description>Data directory</description>
    <srcpath>..\..\..\..\..\ProgramData\MySQL\MySQLServerData</srcpath>
    <destpath>wfa</destpath>
</dir>
----
. Edite o `mscs_resource_properties.xml` arquivo e faça as seguintes atualizações:
+
.. Execute um localizar/Substituir para o `NA_WFA_DB` nome do serviço e atualize-o para `MYSQL57`.
.. Defina `vip_res <prettyname>` o para o nome do endereço IP virtual:
+
[listing]
----
<resource>
    <type>essential</type>
    <id>vip_res</id>
    <prettyname>WFA IP address</prettyname>
</resource>
----
.. Defina `data_res <prettyname>` o para o nome do disco atribuído ao recurso de disco de compartilhamento:
+
[listing]
----
<resource>
    <type>essential</type>
    <id>datadisk_res</id>
    <prettyname>Cluster Disk 2</prettyname>
</resource>
----
.. Copie os arquivos XML do primeiro nó para o segundo nó:
+
`copy “\\node1\D$\Program Files\NetApp\WFA\bin\ha\*xml” “D:\Program Files\NetApp\WFA\bin\ha”`

.. Execute o comando para unir o segundo nó ao cluster:
+
`D:\Program Files\NetApp\WFA\bin\ha>perl ha_setup.pl --join -t mscs -f E:\`



. No prompt de comando, execute o script ha_setup.pl para mover os dados DO WFA para o local compartilhado e configurar O WFA com MSCS para failover. O script está disponível em WFA_install_location.
+
`perl ha_setup.pl --first [-t type_of_cluster_vcs] [-g cluster_group_name] [-i IP_address_name] [-n cluster_name] [-k shared_disk_resource_name] [-f shared_drive_path]`

+
O script ha_setup.pl espera uma entrada usando o recurso Endereço IP para o cluster MSCS. Ao instalar no MSCS 2016, o recurso precisa ser adicionado pelo nome, não pelo endereço IP, `WFA IP address`. Por exemplo:

+
`perl ha_setup.pl --first -t mscs -g WFA -i "WFA IP address" -n wfa_cluster -k "Cluster Disk 2" -f E:\`

. Verifique se os recursos do MSCS são criados, verificando a mensagem configurada com êxito na saída.
+
[listing]
----
Successfully configured MSCS cluster resources on this node
----
. Pare os serviços WFA do Gerenciador de Cluster de failover:
+
[cols="2*"]
|===
| Para... | Faça isso... 


 a| 
Windows 2012, Windows 2016, Windows 2019
 a| 
.. Selecione *funções de serviço* e, em seguida, selecione a função "WFA" recém-criada.
.. No painel recurso, clique com o botão direito do Mouse em *MYSQL57* e selecione *Take Offline*.
.. No painel recurso, clique com o botão direito do Mouse em *na_WFA_SRV* e selecione *Take Offline*.


|===


O serviço de banco de dados WFA e o serviço de servidor WFA devem ser offline. Os serviços WFA não devem ser interrompidos dos serviços do Windows.

. Mova manualmente os recursos DO WFA para o nó secundário.
. Verifique se o disco compartilhado está acessível a partir do segundo nó.
. No prompt de comando, execute o script ha_setup.pl no nó secundário do cluster para configurar O WFA para usar os dados do local compartilhado:
+
`perl ha_setup.pl --join [-t type_of_cluster_mscs] [-f shared_drive_path]`

+
O script ha_setup.pl está disponível em WFA_install_location.

+
`perl ha_setup.pl --join -t mscs -f E:\`

. No Gerenciador de Cluster de failover, coloque os recursos DO WFA online:
+
[cols="2*"]
|===
| Para... | Faça isso... 


 a| 
Windows 2012, Windows 2016, Windows 2019
 a| 
.. Clique com o botão direito do Mouse na função recém-criada "WFA" e selecione *Start role*. A função deve estar no status Running (execução) e os recursos individuais devem estar no estado Online (Online).


|===
. Mude manualmente para o segundo nó do cluster MSCS.
. Verifique se os serviços DO WFA são iniciados corretamente no segundo nó do cluster.

