---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: A caixa de diálogo novas credenciais permite criar uma nova credencial. 
---
= Caixa de diálogo novas credenciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo novas credenciais permite criar uma nova credencial.



== Parâmetros de credencial

Você pode definir os seguintes parâmetros para a credencial recém-criada:

* *Match*
+
Permite selecionar o tipo de correspondência da credencial, que define a credencial para um endereço IP específico ou nome de host, ou toda uma sub-rede ou intervalo IP. Pode selecionar uma das seguintes opções:

+
** Exato: Define credenciais para um IP ou nome de host específico
** Padrão: Define credenciais para o intervalo de nomes do host ou toda a sub-rede ou intervalo IP
+
Pattern é uma expressão regular que é usada para combinar uma cadeia de carateres. Por exemplo, `10.10.10.` corresponde a qualquer IP no intervalo de 10.10.10.0 a 10.10.10.255 e `host` corresponde a todos os nomes de host começando com `host`.



* *Tipo*
+
Permite selecionar o tipo de host na lista suspensa.

+

NOTE: O VMware vCenter não é compatível com Linux.

* *Nome/IP*
+
Permite especificar o nome do host ou o endereço IP da credencial.

* *Nome de usuário*
+
Permite especificar um nome de usuário para a credencial.

* *Senha*
+
Permite especificar uma palavra-passe para o nome de utilizador que criou para a credencial.

* *Substituir valores padrão*
+
Permite substituir os valores padrão do protocolo, da porta e do tempo limite associados ao tipo de sistema remoto selecionado para a credencial.

+
Por predefinição, esta caixa de verificação não está selecionada. Tem de selecionar a caixa de verificação se pretender substituir os valores predefinidos.





== Botões de comando

* *Teste*
+
Permite testar a conexão com o host ou endereço IP efetuando login usando as credenciais necessárias.

* *Guardar*
+
Guarda as definições de configuração e fecha a caixa de diálogo.

* *Cancelar*
+
Cancela as alterações, se houver, e fecha a caixa de diálogo.


