---
permalink: help/reference-edit-active-directory-group-dialog-box.html 
sidebar: sidebar 
keywords: edit, active directory, dialog box, enable, view, modify, oncommand, workflow, automation, group 
summary: A caixa de diálogo Editar grupo do ative Directory permite exibir e modificar as configurações de grupo do ative Directory do OnCommand Workflow Automation. 
---
= Caixa de diálogo Editar Grupo do ative Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Editar grupo do ative Directory permite exibir e modificar as configurações de grupo do ative Directory do OnCommand Workflow Automation.

Dependendo do Privileges e da função do grupo do ative Directory, talvez você não tenha acesso à janela grupos do ative Directory. No entanto, você pode editar as configurações do seu grupo do ative Directory selecionando *Configurações* e, em *Gerenciamento*, clique em *grupos do ative Directory*.


NOTE: Os campos que estão disponíveis para edição dependem do grupo Privileges do ative Directory.

* *Nome do grupo*
+
Exibe o nome do grupo para o grupo do ative Directory.

* *Função*
+
Exibe a função atribuída para a conta de usuário.

+
Exibe uma das seguintes funções de grupo atribuídas ao grupo do ative Directory:

+
** *Hóspede*
+
Esse grupo só pode exibir o status de uma execução de fluxo de trabalho ou ser notificado sobre uma alteração no status de uma execução de fluxo de trabalho.

** *Operador*
+
Este grupo tem permissão para visualizar e executar os fluxos de trabalho para os quais o grupo é fornecido acesso.

** *Aprovador*
+
Este grupo tem permissão para visualizar, executar, aprovar e rejeitar os fluxos de trabalho para os quais o grupo recebe acesso.

+

NOTE: Você deve fornecer o ID de e-mail do aprovador e o status do fluxo de trabalho que deve ser notificado ao aprovador. Se houver vários aprovadores, você poderá fornecer um ID de e-mail do grupo no campo *e-mail*.

** *Arquiteto*
+
Esse grupo tem acesso total para criar fluxos de trabalho, mas está impedido de modificar as configurações globais do SERVIDOR WFA.

** *Admin*
+
Este grupo tem acesso completo ao servidor WFA.

+

NOTE: Você deve configurar pelo menos um grupo de administradores.



* *E-mail*
+
Especifica o e-mail para o grupo do ative Directory para o qual as notificações são enviadas se a opção *Notify On* estiver selecionada.

* *Notificar em*
+
Permite que você selecione quando o grupo de diretórios ativos deve ser notificado por e-mail durante a execução do fluxo de trabalho acionada por esse grupo de diretórios ativos. Você pode selecionar qualquer combinação das seguintes opções:

+
** Execução do fluxo de trabalho iniciada: Notifica o usuário quando a execução do fluxo de trabalho começa.
** Falha na execução do fluxo de trabalho/parcialmente bem-sucedida: Notifica o usuário se a execução do fluxo de trabalho falhar ou se o fluxo de trabalho foi executado com sucesso mesmo que uma ou mais etapas falharam.
+
A execução é concluída porque as etapas com falha foram configuradas para permitir que a execução do fluxo de trabalho continue mesmo quando a etapa falha.

** Execução do fluxo de trabalho concluída com êxito: Notifica o utilizador quando a execução do fluxo de trabalho é concluída com êxito.
** Execução do fluxo de trabalho aguardando aprovação: Notifica o usuário se a execução do fluxo de trabalho estiver aguardando aprovação de um usuário Operator ou Architect, dependendo da configuração DO WFA.






== Botões de comando

* *Guardar*
+
Guarda as definições de configuração e fecha a caixa de diálogo.

* *Cancelar*
+
Cancela as alterações, se houver, e fecha a caixa de diálogo.


