---
permalink: help/reference-edit-finder-dialog-box.html 
sidebar: sidebar 
keywords: edit, finder, dialog box, enable 
summary: A caixa de diálogo Editar Finder permite editar o localizador. 
---
= Caixa de diálogo Editar Finder
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Editar Finder permite editar o localizador.

* Separador Propriedades
* Filtros
* Guia atributos retornados




== Separador Propriedades

A guia *Propriedades* permite editar o nome do localizador, o tipo de objeto dicionário WFA e a descrição do localizador. O separador também apresenta os parâmetros de entrada do filtro utilizado no localizador.

* *Nome*
+
Permite editar o nome do localizador.

* *Tipo*
+
Permite que você selecione o tipo de objeto dicionário WFA na lista, como agregado, grupo e cluster. Os filtros para o objeto selecionado são exibidos na guia *filtros*.

* *Versão da entidade*
+
Permite-lhe introduzir o número da versão para o localizador em `major.minor.revision` formato - por exemplo, 1,0.0.

* *Descrição*
+
Permite editar a descrição do localizador.

* *Tabela de parâmetros de entrada*
+
Apresenta os parâmetros de entrada dos filtros selecionados.





== Separador filtros

Permite selecionar os filtros necessários na lista de filtros disponíveis.

* *Filtros disponíveis*
+
Exibe a lista de filtros disponíveis para o objeto selecionado na guia *Propriedades*.

* *Filtros selecionados*
+
Apresenta a lista de filtros selecionados a partir dos filtros disponíveis.

* *Botões de seleção*
+
Move a entrada selecionada de uma caixa para outra.





== Guia atributos retornados

Permite que você veja detalhes sobre os filtros disponíveis, selecione os atributos necessários dos filtros disponíveis e especifique a ordem de classificação para os atributos.

* *Disponível*
+
Exibe os filtros disponíveis e os atributos dos filtros.

* *Selecionado*
+
Exibe os filtros selecionados e os atributos, os aliases e a ordem de classificação dos filtros selecionados.

* *Botões de comando*
+
** *Para cima*
+
Move a entrada selecionada para cima uma linha na tabela selecionada.

** *Para baixo*
+
Move a entrada selecionada para baixo uma linha na tabela selecionada.

** *Botões de seleção*
+
Move a entrada selecionada de uma tabela para outra.







== Botões de comando

* *Teste*
+
Permite-lhe testar o localizador que selecionou para editar.

* *Guardar*
+
Salva as alterações e fecha a caixa de diálogo.

* *Cancelar*
+
Não salva as alterações, se houver, e fecha a caixa de diálogo.


