---
permalink: help/reference-new-data-source-dialog-box.html 
sidebar: sidebar 
keywords: new, data, source, dialog box, enable, add 
summary: A caixa de diálogo Nova fonte de dados permite adicionar uma nova fonte de dados. 
---
= Caixa de diálogo Nova fonte de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Nova fonte de dados permite adicionar uma nova fonte de dados.



== Propriedades de Configuração da fonte de dados

* *Nome*
+
Permite especificar um nome para a fonte de dados.

* *Tipo de fonte de dados*
+
Permite selecionar o tipo de fonte de dados - por exemplo, Active IQ Unified Manager - 6,0 (MYSQL).

+
Quando você seleciona um tipo de fonte de dados, os campos porta, esquema, nome de usuário, senha, intervalo (minutos) e tempo limite (seg) são preenchidos com dados.

+

NOTE: Se você deseja executar fluxos de trabalho de proteção de dados OnCommand Workflow Automation (WFA) de um servidor Active IQ Unified Manager, você deve configurar O WFA no servidor Active IQ Unified Manager.

+
Para obter mais informações, consulte _Ajuda on-line do Gerenciador Unificado do OnCommand_.

* *Nome do anfitrião*
+
Permite especificar o nome do host ou o endereço IP (IPv4 ou IPv6) para a fonte de dados.

+

NOTE: O tipo de fonte de dados Active IQ Unified Manager não suporta endereços IPv6.

* *Porto*
+
Exibe o número da porta associada, se houver, para o tipo de fonte de dados selecionado.

+
Você pode alterar a porta padrão e especificar uma porta diferente para a fonte de dados.

* * Esquema*
+
Exibe o esquema associado ao tipo de fonte de dados selecionado - por exemplo _cm_storage_ para Active IQ Unified Manager - 6,0 (MYSQL).

+
Esta propriedade não pode ser modificada.

* *Nome de utilizador*
+
Exibe o nome de usuário associado, se houver, para o tipo de fonte de dados selecionado.

+
Você deve especificar o nome de usuário apropriado para essa fonte de dados para substituir o nome de usuário padrão:

+
** Para o Active IQ Unified Manager 6,0 e posterior, você deve inserir o nome de usuário da conta de usuário do banco de dados que você criou no servidor Active IQ Unified Manager.
** Para o Consultor de desempenho, você deve inserir o nome de usuário de um usuário do Active IQ Unified Manager com uma função mínima de GlobalRead.


* *Senha*
+
Permite especificar uma palavra-passe para o tipo de fonte de dados selecionado.

+
Você deve especificar uma senha para substituir a senha padrão para o nome de usuário desta fonte de dados:

+
** Para o Active IQ Unified Manager 6,0 e posterior, você deve inserir a senha da conta de usuário do banco de dados que você criou no servidor Active IQ Unified Manager.
** Para o Consultor de desempenho, você deve inserir a senha de um usuário do Active IQ Unified Manager com uma função mínima de GlobalRead.


* *Base de dados*
* *Intervalo (minutos)*
+
Permite clicar no valor e selecionar um intervalo (em minutos) utilizando as setas para cima e para baixo.

+

NOTE: Se o intervalo estiver definido para zero (0), a amostragem automática é desativada.

+
O intervalo predefinido para a amostragem de dados é:

+
** Tipo de fonte de dados baseada em script: 1440 (desempenho e vc)
** Tipo de fonte de dados baseada em SQL: 30 (cm_storage, armazenamento e cm_performance)


* *Consulte o Guia de instruções de configuração*
+
Abre a caixa de diálogo Setup Instruction Guide (Guia de instruções de configuração), que permite especificar as instruções para configurar a fonte de dados.





== Botões de comando

* *Guardar*
+
Salva as configurações e fecha a caixa de diálogo.

* *Cancelar*
+
Cancela as alterações, se houver, e fecha a caixa de diálogo.


