---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: A caixa de diálogo Editar credenciais permite modificar uma credencial existente. 
---
= Caixa de diálogo Editar credenciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Editar credenciais permite modificar uma credencial existente.



== Parâmetros de credencial

* *Match*
+
Permite selecionar o tipo de correspondência da credencial, que define a credencial para um endereço IP específico ou nome de host, ou toda uma sub-rede ou intervalo IP. As opções disponíveis incluem o seguinte:

+
** Exato: Define um endereço IP específico ou nome de host
** Padrão: Define uma sub-rede inteira ou intervalo IP


* *Tipo*
+
Permite selecionar o tipo de credencial na lista suspensa.

+
O VMware vCenter não é compatível com Linux.

* *Nome/IP*
+
Permite especificar o nome do host ou o endereço IP da credencial.

* *Nome de usuário*
+
Permite especificar o nome de utilizador da credencial.

* *Senha*
+
Permite especificar a palavra-passe para o nome de utilizador.

* *Substituir valores padrão*
+
Permite substituir os valores padrão do protocolo, da porta e do tempo limite associados ao tipo de sistema remoto selecionado para a credencial.

+
Por predefinição, esta caixa de verificação não está selecionada. Tem de selecionar a caixa de verificação se pretender substituir os valores predefinidos.





== Tabela de protocolos

A tabela de protocolos exibe os números de portas e os limites de tempo limite (em segundos) para os protocolos associados ao sistema remoto selecionado para a credencial.



== Botões de comando

* *Teste*
+
Permite testar a conexão com o nome do host ou o endereço IP efetuando login usando as credenciais necessárias.

* *Guardar*
+
Guarda as definições de configuração e fecha a caixa de diálogo.

* *Cancelar*
+
Cancela as alterações, se houver, e fecha a caixa de diálogo.


