---
permalink: help/reference-clone-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: clone, command, definition, dialog box, enable, copy, edit 
summary: 'A caixa de diálogo Clone Command Definition (Definição do comando Clone) permite copiar um comando e editar o comando clonado.' 
---
= Caixa de diálogo Definição do comando clone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Clone Command Definition (Definição do comando Clone) permite copiar um comando e editar o comando clonado.

* Separador Propriedades
* Guia Código
* Separador parâmetros Definição
* Separador Mapeamento de parâmetros
* Separador reserva
* Separador Verificação




== Separador Propriedades

Permite editar as propriedades do comando clonado, como nome, descrição e versão da entidade.

* *Nome*
+
Permite editar o nome do comando clonado. Por padrão, o nome do comando que você selecionou para clonar é usado como o nome do clone, anexado com "'- copy".

* *Versão da entidade*
+
Permite editar o número da versão do comando em `major.minor.revision` formato - por exemplo, 1,0.0.

* *Descrição*
+
Permite editar a descrição do comando.

* * Representação de cordas*
+
Permite especificar uma representação de cadeia de carateres para o comando usando a sintaxe MVFLEX Expression Language (MVEL). Você deve especificar a representação da cadeia de carateres para salvar o comando.

* *Tempo limite (s)*
+
Permite especificar o valor de tempo limite (em segundos) para o comando. O valor padrão é de 600 segundos.

* *Tipo de comando*
+
Permite especificar o tipo de execução do comando.

+
** * Execução padrão*
+
Permite que o comando seja executado sem qualquer período de espera. A execução padrão é selecionada por padrão.

** *Aguarde a condição*
+
Permite especificar o tempo (em segundos) para o qual o comando tem que esperar antes da execução. O valor padrão é de 60 segundos.



* *Versões mínimas de software*
+
Especifica as versões mínimas do software necessárias para que o comando funcione. Por exemplo, o software pode ser agrupado em cluster Data ONTAP 8.2,0 e vCenter 6,0. As versões são exibidas como valores separados por vírgulas.

* * Reter scripts de reserva e verificação a partir do comando original*
+
Permite que você mantenha os scripts de reserva e verificação que foram originalmente especificados para o comando que você deseja clonar.





== Guia Código

Permite editar o código para o comando.

* *Discover Parameters*
+
Copia os parâmetros definidos no código PowerShell para a tabela Definição de parâmetros e a tabela Mapeamento de parâmetros.





== Separador parâmetros Definição

Exibe os parâmetros definidos no código que você inseriu na guia Código.

* *Nome*
+
Exibe o nome do parâmetro.

* *Descrição*
+
Apresenta a descrição do parâmetro.

* *Obrigatório*
+
Exibe uma caixa de seleção selecionada para os parâmetros obrigatórios.

* *Tipo*
+
Exibe o tipo do parâmetro, como string ou enum.

* *Valores*
+
Exibe os valores definidos para o parâmetro.

* *Adicionar parâmetro*
+
Permite adicionar um parâmetro ao comando se a linguagem de script selecionada for Perl.

* *Remover parâmetro*
+
Permite remover um parâmetro do comando se a linguagem de script selecionada for Perl.





== Separador Mapeamento de parâmetros

Permite mapear os parâmetros para objetos de dicionário e especificar o atributo e o nome do objeto.

* *Nome*
+
Exibe o nome do parâmetro.

* *Tipo*
+
Permite selecionar um objeto de dicionário para o parâmetro.

* *Atributo*
+
Permite especificar o atributo necessário. Você pode selecionar o atributo (se disponível) ou inserir o nome do atributo.

* *Nome do objeto*
+
Permite especificar um nome para o objeto dicionário.





== Separador reserva

Permite que você reserve os recursos necessários pelo comando.

* *Script de reserva*
+
Permite que você insira uma consulta SQL para reservar os recursos necessários pelo comando. Isso ajuda a garantir que os recursos necessários estejam disponíveis durante uma execução de fluxo de trabalho agendada.

* *Representação de reservas*
+
Permite especificar uma representação de cadeia de carateres para a reserva usando a sintaxe MVEL. A representação de cadeia de carateres é usada para exibir os detalhes da reserva na janela Reservas.





== Separador Verificação

Permite verificar uma reserva e remover a reserva após a execução do comando.

* *Script de Verificação*
+
Permite que você insira uma consulta SQL para verificar o uso dos recursos que foram reservados pelo script de reserva. O script de verificação também verifica se o cache WFA está atualizado e remove a reserva após uma aquisição de cache.

* *Verificação de teste*
+
Abre a caixa de diálogo Verificação, que permite testar os parâmetros do script de verificação.





== Botões de comando

* *Teste*
+
Abre a caixa de diálogo Testing Command <CommandName> in <ScriptLanguage>, que permite testar o comando.

* *Guardar*
+
Salva o comando e fecha a caixa de diálogo.

* *Cancelar*
+
Cancela as alterações, se houver, e fecha a caixa de diálogo.


