---
permalink: help/task-configure-mail.html 
sidebar: sidebar 
keywords: configure, oncommand, workflow, automation, email, notifications, operations, fail 
summary: 'Você pode configurar o OnCommand Workflow Automation (WFA) para enviar notificações por e-mail sobre operações de fluxo de trabalho, por exemplo, fluxo de trabalho iniciado ou falha no fluxo de trabalho.' 
---
= Configurar notificações por e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o OnCommand Workflow Automation (WFA) para enviar notificações por e-mail sobre operações de fluxo de trabalho - por exemplo, fluxo de trabalho iniciado ou falha no fluxo de trabalho.

*O que você vai precisar*

Você deve ter configurado um host de e-mail em seu ambiente.

.Passos
. Faça login NO WFA através de um navegador da Web como administrador.
. Clique em *Configurações* e, em *Configuração*, clique em *Mail*.
. Introduza as informações necessárias nos campos.
. *Opcional:* Teste as configurações de e-mail executando as seguintes etapas:
+
.. Clique em *Enviar e-mail de teste*.
.. Na caixa de diálogo *conexão de teste*, insira o endereço de e-mail para o qual você deseja enviar o e-mail.
.. Clique em *Teste*.


. Clique em *Salvar*.

